// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpJ2C9_H9WfRo68_8GkCv75wDR8b1_6I8',
    appId: '1:331776982510:android:f7fe6412ae533d43f262ff',
    messagingSenderId: '331776982510',
    projectId: 'medlandia-bd805',
    storageBucket: 'medlandia-bd805.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAASMc52Bb8LZkMbpedEthCX8EYqxniofY',
    appId: '1:331776982510:ios:ecebf1d28190aa88f262ff',
    messagingSenderId: '331776982510',
    projectId: 'medlandia-bd805',
    storageBucket: 'medlandia-bd805.firebasestorage.app',
    iosBundleId: 'org.insus.medlandia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAASMc52Bb8LZkMbpedEthCX8EYqxniofY',
    appId: '1:331776982510:ios:2c79dc2708841c4bf262ff',
    messagingSenderId: '331776982510',
    projectId: 'medlandia-bd805',
    storageBucket: 'medlandia-bd805.firebasestorage.app',
    iosBundleId: 'com.example.medlandia',
  );

}